app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: usuarios

app.product:
    resource: "@AppBundle/Controller/ProductoController.php"
    type:     annotation
    prefix: productos

app.gfd:
    resource: "@AppBundle/Controller/gfdController.php"
    type:     annotation
    prefix: formularioExamen
