<?php

namespace AppBundle\Repository;

/**
 * gfdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gfdRepository extends \Doctrine\ORM\EntityRepository
{
}
